import { describe, it, expect } from 'vitest'
import { calculate, bracketTax, ficaTax } from './calc'
import { DEFAULT_RATES_2026, DEFAULT_INPUTS } from './defaultRates'
import type { Inputs } from './types'

const RATES = DEFAULT_RATES_2026

// Parity tolerance: results must match the reference to a hundredth of a cent.
const CENTS = 6

describe('engine parity — Single, $180,000 (authoritative Excel values)', () => {
  // These targets are the exact computed outputs from the source workbook.
  const r = calculate(DEFAULT_INPUTS, RATES)

  it('contributions subtotal', () => {
    expect(r.nyc.contributions.subtotal).toBeCloseTo(28900, CENTS)
  })

  it('federal income tax (shared across locations)', () => {
    expect(r.nyc.taxes.federalIncome).toBeCloseTo(24998, CENTS)
    expect(r.seattle.taxes.federalIncome).toBeCloseTo(24998, CENTS)
    expect(r.sfBay.taxes.federalIncome).toBeCloseTo(24998, CENTS)
  })

  it('FICA (shared across locations)', () => {
    expect(r.nyc.taxes.fica).toBeCloseTo(13433.4, CENTS)
  })

  it('NYC: state, city, and PFL', () => {
    expect(r.nyc.taxes.stateIncome).toBeCloseTo(7874.65, CENTS)
    expect(r.nyc.taxes.cityLocal).toBeCloseTo(5421.726, CENTS)
    expect(r.nyc.taxes.nyPfl).toBeCloseTo(400, CENTS)
  })

  it('Seattle: WA Cares + WA PFML, no income tax', () => {
    expect(r.seattle.taxes.stateIncome).toBe(0)
    expect(r.seattle.taxes.cityLocal).toBe(0)
    expect(r.seattle.taxes.waCares).toBeCloseTo(1044, CENTS)
    expect(r.seattle.taxes.waPfml).toBeCloseTo(1452.6, CENTS)
  })

  it('SF Bay: CA state (net credit) + CA SDI', () => {
    expect(r.sfBay.taxes.stateIncome).toBeCloseTo(10315.204, CENTS)
    expect(r.sfBay.taxes.caSdi).toBeCloseTo(2340, CENTS)
  })

  it('tax subtotals', () => {
    expect(r.nyc.taxes.subtotal).toBeCloseTo(52127.776, CENTS)
    expect(r.seattle.taxes.subtotal).toBeCloseTo(40928, CENTS)
    expect(r.sfBay.taxes.subtotal).toBeCloseTo(51086.604, CENTS)
  })

  it('cash take-home', () => {
    expect(r.nyc.cashTakeHome).toBeCloseTo(98972.224, CENTS)
    expect(r.seattle.cashTakeHome).toBeCloseTo(110172, CENTS)
    expect(r.sfBay.cashTakeHome).toBeCloseTo(100013.396, CENTS)
  })

  it('total value retained', () => {
    expect(r.nyc.totalValueRetained).toBeCloseTo(127872.224, CENTS)
    expect(r.seattle.totalValueRetained).toBeCloseTo(139072, CENTS)
    expect(r.sfBay.totalValueRetained).toBeCloseTo(128913.396, CENTS)
  })

  it('effective tax rate', () => {
    expect(r.nyc.effectiveTaxRate).toBeCloseTo(0.289598755555556, 12)
    expect(r.seattle.effectiveTaxRate).toBeCloseTo(0.227377777777778, 12)
    expect(r.sfBay.effectiveTaxRate).toBeCloseTo(0.283814466666667, 12)
  })

  it('take-home rate', () => {
    expect(r.nyc.takeHomeRate).toBeCloseTo(0.549845688888889, 12)
    expect(r.seattle.takeHomeRate).toBeCloseTo(0.612066666666667, 12)
    expect(r.sfBay.takeHomeRate).toBeCloseTo(0.555629977777778, 12)
  })

  it('tax saved by contributions', () => {
    expect(r.nyc.taxSavedByContrib).toBeCloseTo(10097.864, CENTS)
    expect(r.seattle.taxSavedByContrib).toBeCloseTo(7272.6, CENTS)
    expect(r.sfBay.taxSavedByContrib).toBeCloseTo(9551.1, CENTS)
  })

  it('taxes-if-zero-contrib baseline', () => {
    expect(r.nyc.taxesIfZeroContrib).toBeCloseTo(62225.64, CENTS)
    expect(r.seattle.taxesIfZeroContrib).toBeCloseTo(48200.6, CENTS)
    expect(r.sfBay.taxesIfZeroContrib).toBeCloseTo(60637.704, CENTS)
  })
})

describe('engine — Married Filing Jointly regression', () => {
  // Reference values generated by the Python oracle that exactly reproduces the
  // authoritative Single-case Excel outputs. Case: $260k MFJ, 401k $24,500,
  // family HSA $8,750, Dependent-Care FSA $5,000.
  const mfj: Inputs = {
    grossSalary: 260000,
    filingStatus: 'Married Filing Jointly',
    contrib401k: 24500,
    hsa: 8750,
    healthFsa: 0,
    dependentCareFsa: 5000,
    traditionalIra: 0,
    otherPreTax: 0,
  }
  const r = calculate(mfj, RATES)

  it('contributions subtotal', () => {
    expect(r.nyc.contributions.subtotal).toBeCloseTo(38250, CENTS)
  })

  it('shared federal + FICA', () => {
    expect(r.nyc.taxes.federalIncome).toBeCloseTo(31125.0, CENTS)
    expect(r.nyc.taxes.fica).toBeCloseTo(15009.625, CENTS)
  })

  it('per-location state/local taxes', () => {
    expect(r.nyc.taxes.stateIncome).toBeCloseTo(10996.05, CENTS)
    expect(r.nyc.taxes.cityLocal).toBeCloseTo(7748.238, CENTS)
    expect(r.sfBay.taxes.stateIncome).toBeCloseTo(13143.908, CENTS)
    expect(r.seattle.taxes.waCares).toBeCloseTo(1508.0, CENTS)
    expect(r.seattle.taxes.waPfml).toBeCloseTo(1488.915, CENTS)
  })

  it('tax subtotals', () => {
    expect(r.nyc.taxes.subtotal).toBeCloseTo(65278.913, CENTS)
    expect(r.seattle.taxes.subtotal).toBeCloseTo(49131.54, CENTS)
    expect(r.sfBay.taxes.subtotal).toBeCloseTo(62658.533, CENTS)
  })

  it('cash take-home', () => {
    expect(r.nyc.cashTakeHome).toBeCloseTo(156471.087, CENTS)
    expect(r.seattle.cashTakeHome).toBeCloseTo(172618.46, CENTS)
    expect(r.sfBay.cashTakeHome).toBeCloseTo(159091.467, CENTS)
  })

  it('tax saved by contributions', () => {
    expect(r.nyc.taxSavedByContrib).toBeCloseTo(12771.695, CENTS)
    expect(r.seattle.taxSavedByContrib).toBeCloseTo(9032.375, CENTS)
    expect(r.sfBay.taxSavedByContrib).toBeCloseTo(11775.875, CENTS)
  })

  it('Additional Medicare kicks in above the $250k MFJ threshold', () => {
    // FICA wage = 260000 - 8750 - 5000 = 246250 (below 250k) → no addl Medicare here.
    // Verify the rule directly with a wage above the threshold:
    const fica = ficaTax(300000, RATES.params, 'Married Filing Jointly')
    // SS capped + Medicare on all + 0.9% on (300000-250000)
    const expected =
      0.062 * 184500 + 0.0145 * 300000 + 0.009 * (300000 - 250000)
    expect(fica).toBeCloseTo(expected, CENTS)
  })
})

describe('engine — edge cases & invariants', () => {
  const base: Inputs = { ...DEFAULT_INPUTS }

  it('zero salary & zero contributions yields zero everywhere and no NaN rates', () => {
    const r = calculate(
      {
        ...base,
        grossSalary: 0,
        contrib401k: 0,
        hsa: 0,
        healthFsa: 0,
        dependentCareFsa: 0,
        traditionalIra: 0,
        otherPreTax: 0,
      },
      RATES,
    )
    expect(r.nyc.taxes.subtotal).toBe(0)
    expect(r.nyc.cashTakeHome).toBe(0)
    expect(r.nyc.effectiveTaxRate).toBe(0) // ratio() guards divide-by-zero
    expect(r.nyc.takeHomeRate).toBe(0)
    expect(Number.isNaN(r.nyc.effectiveTaxRate)).toBe(false)
  })

  it('with zero contributions, actual taxes equal the baseline', () => {
    const noContrib: Inputs = {
      ...base,
      contrib401k: 0,
      hsa: 0,
      healthFsa: 0,
      dependentCareFsa: 0,
      traditionalIra: 0,
      otherPreTax: 0,
    }
    const r = calculate(noContrib, RATES)
    expect(r.nyc.taxSavedByContrib).toBeCloseTo(0, CENTS)
    expect(r.nyc.taxes.subtotal).toBeCloseTo(r.nyc.taxesIfZeroContrib, CENTS)
  })

  it('Social Security is capped at the wage base', () => {
    // Very high salary: SS portion never exceeds rate * wage base.
    const r = calculate({ ...base, grossSalary: 1_000_000, contrib401k: 0, hsa: 0 }, RATES)
    const ssMax = RATES.params.ssRate * RATES.params.ssWageBase
    // FICA = SS(capped) + Medicare + addl; isolate isn't trivial, so re-derive:
    const fica = ficaTax(1_000_000, RATES.params, 'Single')
    expect(fica).toBeGreaterThan(ssMax)
    expect(r.nyc.taxes.fica).toBeCloseTo(fica, CENTS) // hsa/401k=0 → ficaWage=gross
  })

  it('CA shields the HSA from FICA but not from CA income tax', () => {
    // Two scenarios differing only by HSA: CA income tax should be identical,
    // because CA does not allow the HSA deduction.
    const withHsa = calculate({ ...base, hsa: 4400, contrib401k: 0 }, RATES)
    const noHsa = calculate({ ...base, hsa: 0, contrib401k: 0 }, RATES)
    expect(withHsa.sfBay.taxes.stateIncome).toBeCloseTo(noHsa.sfBay.taxes.stateIncome, CENTS)
    // But FICA is lower with the HSA (HSA reduces the FICA base).
    expect(withHsa.sfBay.taxes.fica).toBeLessThan(noHsa.sfBay.taxes.fica)
  })

  it('401(k) lowers income tax but not FICA', () => {
    const with401k = calculate({ ...base, contrib401k: 24500, hsa: 0 }, RATES)
    const no401k = calculate({ ...base, contrib401k: 0, hsa: 0 }, RATES)
    expect(with401k.nyc.taxes.federalIncome).toBeLessThan(no401k.nyc.taxes.federalIncome)
    expect(with401k.nyc.taxes.fica).toBeCloseTo(no401k.nyc.taxes.fica, CENTS)
  })
})

describe('bracketTax helper', () => {
  it('matches a hand-computed federal figure for $135,000 Single taxable', () => {
    // This is the Single $180k case's federal taxable income (180k-28.9k-16.1k).
    expect(bracketTax(135000, RATES.federal, 'Single')).toBeCloseTo(24998, CENTS)
  })

  it('returns 0 for non-positive taxable income', () => {
    expect(bracketTax(0, RATES.federal, 'Single')).toBe(0)
  })
})
